### ISSUE TITLE
installApk Fail

### ISSUE THREAD

**Issue by AlertColby** [react-native-org/react-native-easy-upgrade#11]
Hello, is this feature complete? When I finished downloading apk, an exception occurred during the installation. The exception is shown. How to solve it?
![image](https://user-images.githubusercontent.com/10805985/46136657-bdbed900-c27a-11e8-96b1-7e90ed62869d.png)

**Comment by hstarorg** [comment]
Please provide your phone model and OS version, thanks. The lib in used in our production app.

**Comment by SunnyEver0** [comment]
Please follow those 2 steps check your android `file provider` settings

- make sure your project has already defined file provider in your `AndroidManifest.xml`,just like this:

```
<manifest>
    ...
    <application>
        ...
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            ...
        </provider>
        ...
    </application>
</manifest>
```

- make sure provider `android:authorities` is `"${applicationId}.provider"`
 
After those checks if still not working.please contact again.thanks.

**Comment by hstarorg** [comment]
Can't reproduce, close

**Comment by Xiapeixu** [comment]
> @AlertColby请按照这两个步骤检查你的android `file provider`设置
> 
> * 确保您的项目已经在您的文件提供程序中定义`AndroidManifest.xml`，如下所示：
> 
> ```
> <manifest>
>     ...
>     <application>
>         ...
>         <provider
>             android:name="android.support.v4.content.FileProvider"
>             android:authorities="${applicationId}.provider"
>             android:exported="false"
>             android:grantUriPermissions="true">
>             ...
>         </provider>
>         ...
>     </application>
> </manifest>
> ```
> 
> * 确保提供者`android:authorities`是`"${applicationId}.provider"`
> 
> 在那些检查后仍然无法正常工作。请再次联系。谢谢。

我添加上这段之后,我的app闪退怎么回事?
