### ISSUE TITLE
RN 0.60+ IOS 端会报RNEasyUpgrade.versionName 为null

### ISSUE THREAD

**Issue by roubo** [react-native-org/react-native-easy-upgrade#23]
![image](https://user-images.githubusercontent.com/3437623/68005208-6c6bef00-fcaf-11e9-9b95-467200191141.png)
目前我只能手动修改， 避开报错。

**Comment by hstarorg** [comment]
没有在这个版本下测试，能否提交下 PR 呢？

**Comment by hstarorg** [comment]
@roubo 有什么结论么？
