### ISSUE TITLE
When download new apk failed, next time the new apk cannot installed

### ISSUE THREAD

**Issue by SunnyEver0** [react-native-org/react-native-easy-upgrade#5]
1. download apk file broken with some reason
2. next time to reopen app
3. try to download apk 
4. after download completed, installed failed

**Comment by SunnyEver0** [comment]
Solution:
Before downloading, to delete the old temp file first.
in the new version fix the bug

**Comment by hstarorg** [comment]
Maybe should delete all temp apk files.
